apex_project:
  ros__parameters:
    project_name: "ApexPainterV15 imported project"
    robot_name: "ApexPainterV15"
    description_package: "apexpainterv15_imported_project_description"
    planning_group: "manipulator"
    joint_names:
    - joint_2
    - joint_1
    obstacles:
      - name: "ImportedFixture"
        min: [0.550000, 0.100000, -0.200000]
        max: [0.850000, 0.350000, 0.200000]
      - name: "SafetyZone"
        min: [0.950000, -0.800000, -0.500000]
        max: [1.100000, 0.800000, 0.500000]
