joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
  joint_2:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
