set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(_ars_triplet "x86_64-w64-mingw32")

if(DEFINED ENV{ARS_MINGW_ROOT} AND NOT "$ENV{ARS_MINGW_ROOT}" STREQUAL "")
    set(_ars_tools_root "$ENV{ARS_MINGW_ROOT}")
    set(CMAKE_C_COMPILER "${_ars_tools_root}/bin/${_ars_triplet}-gcc")
    set(CMAKE_CXX_COMPILER "${_ars_tools_root}/bin/${_ars_triplet}-g++")
    set(CMAKE_RC_COMPILER "${_ars_tools_root}/bin/${_ars_triplet}-windres")
    set(CMAKE_AR "${_ars_tools_root}/bin/${_ars_triplet}-ar")
    set(CMAKE_RANLIB "${_ars_tools_root}/bin/${_ars_triplet}-ranlib")
    set(CMAKE_STRIP "${_ars_tools_root}/bin/${_ars_triplet}-strip")
    list(APPEND CMAKE_FIND_ROOT_PATH "$ENV{ARS_MINGW_ROOT}")
else()
    set(CMAKE_C_COMPILER ${_ars_triplet}-gcc)
    set(CMAKE_CXX_COMPILER ${_ars_triplet}-g++)
    set(CMAKE_RC_COMPILER ${_ars_triplet}-windres)
    set(CMAKE_AR ${_ars_triplet}-ar)
    set(CMAKE_RANLIB ${_ars_triplet}-ranlib)
    set(CMAKE_STRIP ${_ars_triplet}-strip)
endif()

if(DEFINED ENV{ARS_MINGW_SYSROOT} AND NOT "$ENV{ARS_MINGW_SYSROOT}" STREQUAL "")
    list(APPEND CMAKE_FIND_ROOT_PATH "$ENV{ARS_MINGW_SYSROOT}")
endif()

if(DEFINED ENV{ARS_CROSS_STAGING_PREFIX} AND NOT "$ENV{ARS_CROSS_STAGING_PREFIX}" STREQUAL "")
    set(CMAKE_STAGING_PREFIX "$ENV{ARS_CROSS_STAGING_PREFIX}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
