function(ars_apply_common_options target_name)
    target_compile_features(${target_name} PUBLIC cxx_std_17)

    if(MSVC)
        target_compile_options(${target_name} PRIVATE /W4 /permissive- /EHsc /Zc:__cplusplus)
        if(ARS_STRICT_WARNINGS)
            target_compile_options(${target_name} PRIVATE /WX)
        endif()
    else()
        target_compile_options(${target_name} PRIVATE -Wall -Wextra -Wpedantic)
        if(ARS_STRICT_WARNINGS)
            target_compile_options(${target_name} PRIVATE -Werror)
        endif()
    endif()
endfunction()
